# 1. NumPy基本操作

## 1.1 列表转为矩阵

In [5]:
import numpy as np
array = np.array([
    [1,3,5],
    [4,6,9]
])
print(array)

[[1 3 5]
 [4 6 9]]


## 1.2 维度

In [6]:
print('number of dim:', array.ndim)

number of dim: 2


## 1.3 行数和列数

In [9]:
print('shape',array.shape)

shape (2, 3)


In [10]:
print('shape',array.shape[0])

shape 2


In [11]:
print('shape',array.shape[1])

shape 3


## 1.4 元素个数

In [12]:
print('size:', array.size)

size: 6


# 2. NumPy创建array

## 2.1 一维array创建

In [14]:
import numpy as np
a = np.array([2,4],dtype=np.int32)
print(a)

[2 4]


## 2.2 多维array创建

In [15]:
a = np.array([[2,3],[3,4]])
print(a)

[[2 3]
 [3 4]]


## 2.3 全0数组

In [22]:
a = np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 2.4 创建全1数组

In [23]:
a = np.ones([3,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2.5 创建全空数组

In [31]:
a = np.empty((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
a = np.empty((3,4))
a.fill(3)
print(a)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


## 2.6 创建连续数组

In [34]:
a = np.arange(10,21,2) # 10-20的数据，步长为2
print(a)

[10 12 14 16 18 20]


## 2.7 reshape操作

In [35]:
b = a.reshape((2,3))
print(b)

[[10 12 14]
 [16 18 20]]


## 2.8 创建连续型数据

In [36]:
a = np.linspace(1,10,20) # 开始端1，结束端10，且分割成20个数据，生成线段
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.9 linspace的reshape操作

In [37]:
b = a.reshape((5,4))
print(b)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


# 3.Numpy基本运算

## 3.1 一维矩阵运算

In [38]:
import numpy as np

a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

[10 20 30 40] [0 1 2 3]


In [39]:
c = a - b
print(c)

[10 19 28 37]


In [40]:
print(a+b)

[10 21 32 43]


In [41]:
print(a * b)

[  0  20  60 120]


In [42]:
print(a.dot(b))

200


In [43]:
print(a.T.dot(b))

200


## 3.2 多维矩阵运算

In [44]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))
print(a)

[[1 1]
 [0 1]]


In [45]:
print(b)

[[0 1]
 [2 3]]


In [47]:
c = a.dot(b)
print(c)

[[2 4]
 [2 3]]


In [48]:
c = np.dot(a,b)
print(c)

[[2 4]
 [2 3]]


In [49]:
a = np.random.random((2,4))
print(np.sum(a)) 
print(np.min(a))
print(np.max(a))
print("a=",a)

3.3159731924231406
0.005120378969071804
0.8830464154162697
a= [[0.86609566 0.00512038 0.4726153  0.1993335 ]
 [0.51774489 0.88304642 0.22228912 0.14972792]]


In [50]:
# 查找 axis=0按列 =1按行
print("sum=",np.sum(a,axis=1))
print("min=",np.min(a,axis=0))
print("max=",np.max(a,axis=1))

sum= [1.54316485 1.77280834]
min= [0.51774489 0.00512038 0.22228912 0.14972792]
max= [0.86609566 0.88304642]


## 3.3 基本计算

In [51]:
import numpy as np

A = np.arange(2,14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [52]:
# 最小元素索引
print(np.argmin(A)) # 0

0


In [53]:
# 最大元素索引
print(np.argmax(A)) # 11

11


In [54]:
# 求整个矩阵的均值
print(np.mean(A)) # 7.5

7.5


In [55]:
print(np.average(A)) # 7.5

7.5


In [56]:
# 中位数
print(np.median(A)) # 7.5

7.5


In [57]:
# 累加
print(np.cumsum(A))

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [58]:
# 累差运算
B = np.array([[3,5,9],
              [4,8,10]])
print(np.diff(B))

[[2 4]
 [4 2]]


In [59]:
# np.nonzero函数用于得到数组array中非零元素的位置
C = np.array([[0,5,9],
              [4,0,10]])
print(np.nonzero(B))
print(np.nonzero(C))

(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))


In [60]:
# 仿照列表排序
A = np.arange(14,2,-1).reshape((3,4)) # -1表示反向递减一个步长
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [61]:
print(np.sort(A))

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [62]:
# 矩阵转置
print(np.transpose(A))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [63]:
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


# 4. NumPy索引与切片

In [64]:
import numpy as np
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [65]:
print(A[3])

6


In [66]:
B = A.reshape(3,4)
print(B)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [67]:
print(B[2])

[11 12 13 14]


In [68]:
# list切片操作
print(B[1,1:3]) # [8 9] 1:3表示1-2不包含3

[8 9]


In [69]:
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [70]:
# 如果要打印列，则进行转置即可
for column in B.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [71]:
# 多维转一维
A = np.arange(3,15).reshape((3,4))
# print(A)
print(A.flatten())
# flat是一个迭代器，本身是一个object属性

[ 3  4  5  6  7  8  9 10 11 12 13 14]


# 5. NumPy array合并

## 5.1 数组合并

In [72]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B)))
# vertical stack 上下合并,对括号的两个整体操作。

[[1 1 1]
 [2 2 2]]


In [73]:
C = np.vstack((A,B))
print(C)

[[1 1 1]
 [2 2 2]]


In [74]:
print(A.shape,B.shape,C.shape)# 从shape中看出A,B均为拥有3项的数组(数列)

(3,) (3,) (2, 3)


In [75]:
# horizontal stack左右合并
D = np.hstack((A,B))
print(D)

[1 1 1 2 2 2]


## 5.2 数组转置为矩阵

In [76]:
print(A[np.newaxis,:]) # [1 1 1]变为[[1 1 1]]

[[1 1 1]]


In [77]:
print(A[np.newaxis,:].shape) # (3,)变为(1, 3)

(1, 3)


In [78]:
print(A[:,np.newaxis])

[[1]
 [1]
 [1]]


## 5.3 多个矩阵合并

In [79]:
# concatenate的第一个例子
print("------------")
print(A[:,np.newaxis].shape) # (3,1)

------------
(3, 1)


In [81]:
A = A[:,np.newaxis] # 数组转为矩阵
B = B[:,np.newaxis] # 数组转为矩阵
print(A)
print(B)

[[[1]]

 [[1]]

 [[1]]]
[[[2]]

 [[2]]

 [[2]]]


In [82]:
# axis=0纵向合并
C = np.concatenate((A,B,B,A),axis=0)
print(C)

[[[1]]

 [[1]]

 [[1]]

 [[2]]

 [[2]]

 [[2]]

 [[2]]

 [[2]]

 [[2]]

 [[1]]

 [[1]]

 [[1]]]


In [83]:
# axis=1横向合并
C = np.concatenate((A,B),axis=1)
print(C)

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]]


# 6. NumPy array分割

## 6.1 构造3行4列矩阵

In [84]:
import numpy as np
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 6.2 等量分割

In [85]:
# 等量分割
# 纵向分割同横向合并的axis
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


## 6.3 不等量分割

In [86]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


# 7. NumPy copy与=

## 7.1 =赋值方式会带有关联性

In [87]:
import numpy as np
# `=`赋值方式会带有关联性
a = np.arange(4)
print(a) # [0 1 2 3]

[0 1 2 3]


In [88]:
b = a
c = a
d = b
a[0] = 11
print(a) # [11  1  2  3]

[11  1  2  3]


In [89]:
print(b) # [11  1  2  3]

[11  1  2  3]


In [90]:
print(c) # [11  1  2  3]

[11  1  2  3]


In [91]:
print(d) # [11  1  2  3]

[11  1  2  3]


In [92]:
print(b is a) # True

True


In [93]:
print(c is a) # True

True


## 7.2 copy()赋值方式没有关联性

In [94]:
a = np.arange(4)
print(a) # [0 1 2 3]

[0 1 2 3]


In [95]:
b =a.copy() # deep copy
print(b) # [0 1 2 3]

[0 1 2 3]


In [96]:
a[3] = 44
print(a) # [ 0  1  2 44]
print(b) # [0 1 2 3]

# 此时a与b已经没有关联

[ 0  1  2 44]
[0 1 2 3]


# 8.广播机制

numpy数组间的基础运算是一对一，也就是a.shape==b.shape，但是当两者不一样的时候，就会自动触发广播机制，如下例子：

In [97]:
from numpy import array
a = array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = array([0,1,2])
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
